### ISSUE TITLE
Potential license

### ISSUE THREAD

**Issue by philtweir** [hearmecode/days-since#1]
Hello! Would it be possible to have a license here, please? I'm assuming, as it's been posted here publicly and a couple of us are keen to use for a non-business purpose, that there's no issue, but wanted to double-check. It's helpful as a nice clean template, so thank you!

**Comment by shannonturner** [comment]
Sure thing! Here you go: https://github.com/hearmecode/days-since/blob/master/LICENSE

**Comment by philtweir** [comment]
Thanks!
